apiVersion: v2
name: safeconvert
description: SafeConvert static frontend served by NGINX
icon: https://raw.githubusercontent.com/spwoodcock/safeconvert/refs/heads/main/public/favicon.ico
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.15.4"
